Project/Models/Entities/Book.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Project.Models.Entities
{
    public class Book
    {
        [HiddenInput(DisplayValue = false)]
        public int BookId { get; set; }

        [Display(Name = "Название")]
        [Required(ErrorMessage = "Пожалуйста, введите название книги")]
        [StringLength(255, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Пожалуйста, введите описание")]
        [StringLength(255, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Description { get; set; }

        [Display(Name = "Категория")]
        [Required(ErrorMessage = "Пожалуйста, введите категирию")]
        [StringLength(32, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Category { get; set; }

        [Display(Name = "Автор")]
        [Required(ErrorMessage = "Пожалуйста, введите автора книги")]
        [StringLength(32, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Author { get; set; }

        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    }
}

Project/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models.Abstract;
using Project.Models.Entities;
using Project.Models;

namespace Project.Controllers
{
    public class BookController : Controller
    {
        private IBookOrderRepository repository;
        public int pageSize = 3;

        public BookController(IBookOrderRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int page = 1)
        {
            BookListViewModel model = new BookListViewModel
            {
                Books = repository.Books
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(book => book.BookId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Books.Count() :
                repository.Books.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                return File(book.ImageData, book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Details(int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);
            if (book != null)
                return PartialView(book);
            return HttpNotFound();
        }

    }
}

Project/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models.Abstract;

namespace Project.Controllers
{
    public class NavigationController : Controller
    {
        private IBookOrderRepository repository;

        public NavigationController(IBookOrderRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Books
                .Select(book => book.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

Project/Controllers/OrderController.cs
using Project.Models.Abstract;
using Project.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Project.Controllers
{
    public class OrderController : Controller
    {
        private IBookOrderRepository repository;

        public OrderController(IBookOrderRepository repo)
        {
            repository = repo;
        }

        public int BookId;
        public string UserId;

        public ViewResult Edit(int bookId)
        {
            Book book = repository.Books.FirstOrDefault(g => g.BookId == bookId);
            TempData["BookName"] = string.Format("Заказ книги \"{0}\"", book.Name);
            Order order = new Order();
            BookId = bookId;
            UserId = User.Identity.GetUserId();
            return View(order);
        }

        // Перегруженная версия Edit() для сохранения изменений
        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                if (order.BookId == 0)
                    order.BookId = BookId;
                if (order.UserId == null)
                    order.UserId = User.Identity.GetUserId();
                repository.SaveOrder(order);
                return RedirectToAction("List", "Book");
            }
            else
            {
                BookId = BookId;
                UserId = UserId;
                Book book = repository.Books.FirstOrDefault(g => g.BookId == order.BookId);
                TempData["BookName"] = string.Format("Заказ книги \"{0}\"", book.Name);
                return View(order);
            }
        }

    }
}

Project/Views/Shared/BookView.cshtml
@model WebApplication1.Entities.Book

    <div class="col-sm-5 col-md-4">
        <div class="thumbnail">
            
            <div class="entry">
                @if (Model.ImageData != null)
                {
                    <div class="text-center">
                        <img class="img-fluid"
                             src="@Url.Action("GetImage", "Book",
                new { Model.BookId })" />
                    </div>
                }
                    <div class="caption">
                        <h2 class="title">  @Model.Name </h2>
                        <p class="lead">@Model.Description.Substring(0, 100)...</p>
                        <p><a href="#" class="btn btn-primary" role="button">Заказать</a> 
                        @Html.ActionLink("Подробнее", "Details", new { Model.BookId })</p>
                    </div>
            </div>
        </div>
    </div>

Project/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Project/Views/Shared/_BookView.cshtml
@model Project.Models.Entities.Book
@using Microsoft.AspNet.Identity;

<div class="col-sm-5 col-md-4">
    <div class="thumbnail">
        <div class="entry">
            <div class="card" style="width: 18rem;">
                @if (Model.ImageData != null)
                {
                    <img src="@Url.Action("GetImage", "Book",
      new { Model.BookId })"
                         class="card-img-center" style="width: 18rem; height: 20rem;">
                }
                <div class="card-body">
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description.Substring(0,10) ...</p>
                    @if (Request.IsAuthenticated)
                    {
                        <a href="@Url.Action("Edit", "Order", new { Model.BookId})" class="btn btn-primary">Заказать</a>
                    }
                    @Html.ActionLink("Подробнее", "Details", new { Model.BookId }, new { @class = "compItem" })
                </div>
            </div>
        </div>
    </div>
</div>

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Библиотека программиста :)", "List", "Book", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Категории <b class="caret"></b></a>
                        @Html.Action("Menu", "Navigation")
                    </li>
                </ul>   
                <div class="navbar-collapse collapse">
                    @Html.Partial("_LoginPartial")
                </div>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    @RenderBody()


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>