Project/Models/Entities/Book.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Project.Models.Entities
{
    public class Book
    {
        [HiddenInput(DisplayValue = false)]
        public int BookId { get; set; }

        [Display(Name = "Название")]
        [Required(ErrorMessage = "Пожалуйста, введите название книги")]
        [StringLength(255, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Описание")]
        [Required(ErrorMessage = "Пожалуйста, введите описание")]
        [StringLength(255, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Description { get; set; }

        [Display(Name = "Категория")]
        [Required(ErrorMessage = "Пожалуйста, введите категирию")]
        [StringLength(32, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Category { get; set; }

        [Display(Name = "Автор")]
        [Required(ErrorMessage = "Пожалуйста, введите автора книги")]
        [StringLength(32, MinimumLength = 2, ErrorMessage = "Недопустимая длина поля")]
        public string Author { get; set; }

        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    }
}

Project/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models.Abstract;
using Project.Models.Entities;
using Project.Models;

namespace Project.Controllers
{
    public class BookController : Controller
    {
        private IBookOrderRepository repository;
        public int pageSize = 3;

        public BookController(IBookOrderRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int page = 1)
        {
            BookListViewModel model = new BookListViewModel
            {
                Books = repository.Books
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(book => book.BookId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Books.Count() :
                repository.Books.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);

            if (book != null)
            {
                return File(book.ImageData, book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Details(int bookId)
        {
            Book book = repository.Books
                .FirstOrDefault(g => g.BookId == bookId);
            if (book != null)
                return PartialView(book);
            return HttpNotFound();
        }

    }
}

Project/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models.Abstract;

namespace Project.Controllers
{
    public class NavigationController : Controller
    {
        private IBookOrderRepository repository;

        public NavigationController(IBookOrderRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Books
                .Select(book => book.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

Project/Views/Book/Details.cshtml
@model Project.Models.Entities.Book

@{
    ViewBag.Title = "Details";
}

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h3 class="text-center h3"> @Html.DisplayFor(model => model.Name)</h3>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            @if (Model.ImageData != null)
            {
                <div class="text-center">
                    <img class="img-fluid"
                         src="@Url.Action("GetImage", "Book",
                new { Model.BookId })" />
                </div>
            }
                <p>
                    <b>
                        @Html.DisplayNameFor(model => model.Category) : 
                    </b>
                    @Html.DisplayFor(model => model.Category)
                </p>
             

            <p>
                <b>
                    @Html.DisplayNameFor(model => model.Description)
                </b>
            </p>

            <p class="text-justify">
                @Html.DisplayFor(model => model.Description)
            </p>
        </dl>
    </div>
</div>

Project/Views/Book/List.cshtml
@using Project.Models
@using Project.HtmlHelpers
@model BookListViewModel

@{
    ViewBag.Title = "Список книг";
}
<div class="row panel">
    <div id="categories" class="col-xs-2">
        <ul class="nav nav-pills nav-stacked">
            @*@Html.Action("Menu", "Navigation")*@
        </ul>
    </div>
    <div class="col-xs-9">
        <div id="modDialog" class="modal fade">
            <div id="dialogContent" class="modal-dialog"></div>
        </div>
        <div class="row">
            @foreach (var p in @Model.Books)
            {
                @Html.Partial("_BookView", p)

            }
        </div>
        @section scripts
{
            <script type="text/javascript">

                $(function () {
                    $.ajaxSetup({ cache: false });
                    $(".compItem").click(function (e) {

                        e.preventDefault();
                        $.get(this.href, function (data) {
                            $('#dialogContent').html(data);
                            $('#modDialog').modal('show');
                        });
                    });
                })
            </script>
        }
        <nav aria-label="Page navigation">
            <div class="btn-group pull-right">
                <ul class="pagination">
                    <li>
                        @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
                            new { page = x, category = Model.CurrentCategory }))
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>